# -*- coding: utf-8 -*-
"""fpl_model4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hg0aC0eub2v0HA6RIvLOY6s8QY_ksKS-
"""

# fpl_model.py
# -*- coding: utf-8 -*-

import pandas as pd
import numpy as np
import requests
import pulp
from functools import lru_cache
from typing import Dict, Any, List, Optional, Tuple

# ============= CONFIG =============
GITHUB_BASE = "https://raw.githubusercontent.com/maxwell-petitjean/fpl/refs/heads/main/"


# -----------------------------
# Low-level helpers
# -----------------------------
def _fetch_json(url: str, timeout: int = 20) -> Any:
    r = requests.get(url, timeout=timeout)
    r.raise_for_status()
    return r.json()


def load_csv(filename: str) -> pd.DataFrame:
    url = GITHUB_BASE + filename
    try:
        return pd.read_csv(url, encoding="utf-8")
    except UnicodeDecodeError:
        return pd.read_csv(url, encoding="latin1")


@lru_cache(maxsize=1)
def get_gw_context() -> Dict[str, Any]:
    """
    Computes current GW + derived vars (cached per process).
    No network calls at import time.
    """
    url0 = "https://fantasy.premierleague.com/api/fixtures?future=1"
    js0 = _fetch_json(url0)
    nxt = pd.DataFrame(js0)[["event"]]
    var_gw = int(pd.to_numeric(nxt["event"], errors="coerce").min())

    ctx = {
        "VAR_GW": var_gw,
        "VAR_GW0": var_gw - 1,  # last completed
        "VAR_GW_LY": 38 - 1,
        "VGW_NAME_1": f"gw{var_gw}",
        "VGW_NAME_2": f"gw{var_gw+1}",
        "VGW_NAME_3": f"gw{var_gw+2}",
        "VGW_NAME_4": f"gw{var_gw+3}",
        "VGW_NAME_5": f"gw{var_gw+4}",
        "VGW_NAME_6": f"gw{var_gw+5}",
    }
    return ctx


# -----------------------------
# Base model builder (your “divorced” block)
# -----------------------------
def build_base_player_pool() -> Dict[str, Any]:
    """
    This is the refactored version of:
      '# ---- Load API data ----'  -->  'output = output.sort_values(...)'

    Returns a dict containing:
      output (pool), player_output (research), fdr_att, fdr_def, ctx
    """
    ctx = get_gw_context()
    VAR_GW = ctx["VAR_GW"]
    VAR_GW0 = ctx["VAR_GW0"]
    VAR_GW_LY = ctx["VAR_GW_LY"]

    # Same constants you had
    VAR_REL1, VAR_REL2, VAR_REL3 = "IPS", "LEI", "SOU"
    VAR_PRO1, VAR_PRO2, VAR_PRO3 = "BUR", "LEE", "SUN"

    URL1 = "https://fantasy.premierleague.com/api/bootstrap-static/"
    URL2 = "https://fantasy.premierleague.com/api/fixtures?future=1"

    # last 10 completed gameweeks: VAR_GW0 back 9
    live_urls = [
        f"https://fantasy.premierleague.com/api/event/{VAR_GW0 - i}/live/"
        for i in range(10)
    ]

    json1 = _fetch_json(URL1)
    json2 = _fetch_json(URL2)
    live_jsons = [_fetch_json(u) for u in live_urls]

    # concatenate live gw dfs
    gw_dfs = [pd.DataFrame(js) for js in live_jsons]
    gw_df = pd.concat(gw_dfs, ignore_index=True)

    # historical csvs
    players_prev0 = load_csv("players_24.csv")
    fixtures_prev0 = load_csv("gws_24.csv")
    teams3 = load_csv("teams_24.csv")
    xm_manual = load_csv("xm_manual.csv")

    # ---- TEAMS
    teams = pd.DataFrame(json1["teams"])[
        [
            "id",
            "name",
            "short_name",
            "strength_attack_home",
            "strength_defence_home",
            "strength_attack_away",
            "strength_defence_away",
        ]
    ]
    teams.columns = ["team_id", "team_name", "team_code", "str_o_h", "str_d_h", "str_o_a", "str_d_a"]

    # ---- POSITIONS
    positions = pd.DataFrame(json1["element_types"])[["id", "singular_name_short"]]
    positions.columns = ["id", "pos"]

    # ---- Players - Previous Seasons
    players_prev1 = players_prev0[["first_name", "second_name", "element_type", "total_points", "minutes"]].copy()
    players_prev1["name"] = players_prev1["first_name"] + " " + players_prev1["second_name"]
    players_prev3 = players_prev1[["name", "minutes", "total_points"]].copy()
    players_prev3.columns = ["name", "minutes", "points"]
    players_prev5 = players_prev3.copy()
    players_prev5["pp90"] = players_prev5["points"] / (players_prev5["minutes"] / 90)
    players_prev6 = players_prev5.fillna(0)
    players_prev6["pp90"] = round(players_prev6["pp90"], 2).clip(upper=10)
    players_prev7 = players_prev6.sort_values("points", ascending=False)

    # ---- FORM -- THIS SEASON
    players = pd.DataFrame(json1["elements"])
    players1 = players[
        [
            "id",
            "first_name",
            "second_name",
            "team",
            "element_type",
            "now_cost",
            "selected_by_percent",
            "clearances_blocks_interceptions",
            "recoveries",
            "tackles",
            "clean_sheets",
            "expected_assists",
            "expected_goals",
            "total_points",
            "minutes",
        ]
    ]
    players2 = (
        players1.merge(teams[["team_id", "team_code"]], left_on="team", right_on="team_id")
        .merge(positions[["id", "pos"]], left_on="element_type", right_on="id")
    )
    players3 = players2.copy()
    players3["name"] = players3["first_name"] + " " + players3["second_name"]
    players3["cbrit"] = players3["clearances_blocks_interceptions"] + players3["recoveries"] + players3["tackles"]
    players4 = players3[
        ["id_x", "name", "team_code", "pos", "now_cost", "selected_by_percent", "cbrit", "clean_sheets", "expected_assists", "expected_goals", "total_points", "minutes"]
    ]
    players4.columns = ["id", "name", "team", "pos", "cost", "ownership", "dc", "cs", "xa", "xg", "points", "mins"]

    # ---- FORM -- LAST 10 (THIS YEAR)
    form0 = pd.json_normalize(gw_df["elements"])
    form1 = form0[
        [
            "id",
            "stats.defensive_contribution",
            "stats.clean_sheets",
            "stats.expected_assists",
            "stats.expected_goals",
            "stats.total_points",
            "stats.minutes",
        ]
    ]
    form1.columns = ["id_form", "dc_form", "cs_form", "xa_form", "xg_form", "points_form", "mins_form"]
    form2 = form1.merge(players4[["id", "name"]], left_on="id_form", right_on="id")
    form3 = form2[["name", "dc_form", "cs_form", "xa_form", "xg_form", "points_form", "mins_form"]].copy()
    form3.columns = ["name_form", "dc_form", "cs_form", "xa_form", "xg_form", "points_form", "mins_form"]
    form3["xa_form"] = form3["xa_form"].astype(float)
    form3["xg_form"] = form3["xg_form"].astype(float)

    # ---- FORM -- LAST 10 (LAST YEAR)
    fixtures_prev1 = fixtures_prev0.drop(fixtures_prev0[fixtures_prev0["GW"] < VAR_GW_LY].index)
    fixtures_prev2 = fixtures_prev1[fixtures_prev1["position"] != "AM"]
    fixtures_prev3 = fixtures_prev2[["name", "cbrit", "clean_sheets", "expected_assists", "expected_goals", "total_points", "minutes"]].copy()
    fixtures_prev3.columns = ["name_form", "dc_form", "cs_form", "xa_form", "xg_form", "points_form", "mins_form"]
    fixtures_prev3["dc_form"] = (fixtures_prev3["mins_form"] / 90) * 5

    # ---- FORM -- CONCATENATE LAST 10
    form4 = pd.concat([form3, fixtures_prev3], ignore_index=True)
    form40 = form4.merge(players4[["name", "pos"]], left_on="name_form", right_on="name")

    # ---- FORM -- CLEAN DATA
    form5 = pd.pivot_table(
        form40,
        values=["dc_form", "cs_form", "xa_form", "xg_form", "points_form", "mins_form"],
        index=["name_form", "pos"],
        aggfunc=[np.sum],
        fill_value=0,
    )
    form6 = form5.reset_index()
    form6.columns = form6.columns.droplevel(0)
    form6.columns = ["name_form", "pos_form", "cs_form", "dc_form", "mins_form", "points_form", "xa_form", "xg_form"]

    form7 = form6.copy()
    form7["xm_form"] = round(form7["mins_form"] / 10, 2)
    form8 = form7.copy()
    form8["pp90_form"] = round(form8["points_form"] / (form8["mins_form"] / 90), 2)

    form9 = form8.copy()
    form9["csp_form"] = round((form9["cs_form"] * 4), 2)
    form9["cspp90_form"] = round(form9["csp_form"] / (form9["mins_form"] / 90), 2)

    form10 = form9.copy()
    form10["xap_form"] = form10["xa_form"] * 3
    form10["xgp_form"] = np.where(
        (form10["pos_form"] == "FWD"),
        form10["xg_form"] * 4,
        np.where(
            (form10["pos_form"] == "MID"),
            form10["xg_form"] * 5,
            np.where((form10["pos_form"].isin(["DEF", "GKP"])), form10["xg_form"] * 6, 0),
        ),
    )
    form10["xop_form"] = form10["xap_form"] + form10["xgp_form"]
    form11 = form10.copy()
    form11["xopp90_form"] = round((form11["xop_form"]) / (form11["mins_form"] / 90), 2)

    form12 = form11.copy()
    form12["dcp_form"] = np.where(
        (form12["pos_form"] == "MID"),
        form12["dc_form"] / 6,
        np.where((form12["pos_form"] == "DEF"), form12["dc_form"] / 5, 0),
    )
    form12["dcp_form"] = round(form12["dcp_form"], 2)
    form12["dcpp90_form"] = round((form12["dcp_form"]) / (form12["mins_form"] / 90), 2).clip(upper=2)
    form12["pred_pp90_form"] = form12["xopp90_form"] + form12["cspp90_form"] + form12["dcpp90_form"] + 2
    form12 = form12.fillna(0)

    # ---- Merge player stats
    players_prev8 = players_prev7.copy()
    players_prev8.columns = ["name_ly", "mins_ly", "points_ly", "pp90_ly"]
    players5 = (
        players4.merge(players_prev8, how="left", left_on="name", right_on="name_ly")
        .merge(form12, how="left", left_on="name", right_on="name_form")
    )

    # ---- Build fixture difficulty
    team_gw_prev1 = fixtures_prev1[["GW", "position", "team", "opponent_team", "was_home", "total_points", "minutes"]].copy()
    team_gw_prev1["played60"] = np.where((team_gw_prev1["minutes"] > 60), 1, 0)
    team_gw_prev2 = team_gw_prev1.drop(team_gw_prev1[team_gw_prev1["played60"] == 0].index)
    team_gw_prev2["pos"] = np.where(team_gw_prev2["position"].isin(["MID", "FWD"]), "ATT", team_gw_prev2["position"])

    team_gw_prev3 = pd.pivot_table(
        team_gw_prev2,
        values=["total_points", "played60"],
        index=["opponent_team", "was_home", "pos"],
        aggfunc=[np.sum],
        fill_value=0,
    ).reset_index()
    team_gw_prev3.columns = team_gw_prev3.columns.droplevel(0)
    team_gw_prev3.columns = ["team", "home", "pos", "players", "points"]

    team_gw_prev4 = team_gw_prev3.copy()
    team_gw_prev4["ppg"] = team_gw_prev4["points"] / team_gw_prev4["players"]
    team_gw_prev5 = team_gw_prev4.copy()
    team_gw_prev5["ppgh"] = np.where(team_gw_prev5["home"] == True, team_gw_prev5["ppg"], 0)
    team_gw_prev5["ppga"] = np.where(team_gw_prev5["home"] == False, team_gw_prev5["ppg"], 0)

    team_gw_prev6 = pd.pivot_table(team_gw_prev5, values=["ppgh", "ppga"], index=["team", "pos"], aggfunc=[np.sum], fill_value=0).reset_index()
    team_gw_prev6.columns = team_gw_prev6.columns.droplevel(0)
    team_gw_prev6.columns = ["team", "pos", "ppgh", "ppga"]

    team_gw_prev7 = team_gw_prev6.merge(teams3[["id", "short_name"]], left_on="team", right_on="id")
    team_gw_prev8 = team_gw_prev7[["short_name", "pos", "ppgh", "ppga"]].copy()
    team_gw_prev8.columns = ["team_code", "pos", "ppgh", "ppga"]

    team_gw_prev8["team_new"] = np.where(
        team_gw_prev8["team_code"] == VAR_REL1,
        VAR_PRO1,
        np.where(
            team_gw_prev8["team_code"] == VAR_REL2,
            VAR_PRO2,
            np.where(team_gw_prev8["team_code"] == VAR_REL3, VAR_PRO3, team_gw_prev8["team_code"]),
        ),
    )
    team_gw_prev9 = team_gw_prev8.merge(teams[["team_code", "team_id"]], left_on="team_new", right_on="team_code")

    # ---- Upcoming fixtures
    fixtures = pd.DataFrame(json2)[["event", "team_h", "team_a"]]
    fixtures2 = fixtures[(fixtures["event"] >= VAR_GW) & (fixtures["event"] <= (VAR_GW + 5))].copy()
    fixtures_h1 = fixtures2.pivot(index="team_h", columns="event", values="team_a").reset_index().fillna(0).astype(int)
    fixtures_a1 = fixtures2.pivot(index="team_a", columns="event", values="team_h").reset_index().fillna(0).astype(int)

    fixtures_h1.columns = ["team_h", "a1", "a2", "a3", "a4", "a5", "a6"]
    fixtures_a1.columns = ["team_a", "h1", "h2", "h3", "h4", "h5", "h6"]

    lookup_team1 = dict(zip(teams["team_id"], teams["team_code"]))
    fixtures_h4 = fixtures_h1.replace(lookup_team1)
    fixtures_a4 = fixtures_a1.replace(lookup_team1)

    # ---- Merge fixtures into players
    fix_att1 = team_gw_prev9[team_gw_prev9["pos"] == "ATT"]
    fix_def1 = team_gw_prev9[team_gw_prev9["pos"] == "DEF"]
    fix_gk1 = team_gw_prev9[team_gw_prev9["pos"] == "GK"]

    lookup_home_att = dict(zip(fix_att1["team_new"], fix_att1["ppgh"]))
    lookup_home_def = dict(zip(fix_def1["team_new"], fix_def1["ppgh"]))
    lookup_home_gk = dict(zip(fix_gk1["team_new"], fix_gk1["ppgh"]))
    lookup_away_att = dict(zip(fix_att1["team_new"], fix_att1["ppga"]))
    lookup_away_def = dict(zip(fix_def1["team_new"], fix_def1["ppga"]))
    lookup_away_gk = dict(zip(fix_gk1["team_new"], fix_gk1["ppga"]))

    fixtures_home_att = fixtures_h4.copy()
    fixtures_home_def = fixtures_h4.copy()
    fixtures_home_gk = fixtures_h4.copy()

    cols_1 = fixtures_home_att.columns[1:]
    fixtures_home_att[cols_1] = fixtures_home_att[cols_1].replace(lookup_away_att)
    fixtures_home_def[cols_1] = fixtures_home_def[cols_1].replace(lookup_away_def)
    fixtures_home_gk[cols_1] = fixtures_home_gk[cols_1].replace(lookup_away_gk)

    fixtures_away_att = fixtures_a4.copy()
    fixtures_away_def = fixtures_a4.copy()
    fixtures_away_gk = fixtures_a4.copy()

    cols_2 = fixtures_away_att.columns[1:]
    fixtures_away_att[cols_2] = fixtures_away_att[cols_2].replace(lookup_home_att)
    fixtures_away_def[cols_2] = fixtures_away_def[cols_2].replace(lookup_home_def)
    fixtures_away_gk[cols_2] = fixtures_away_gk[cols_2].replace(lookup_home_gk)

    new_cols = ["team", "op1", "op2", "op3", "op4", "op5", "op6"]
    for df in [fixtures_home_att, fixtures_home_def, fixtures_home_gk, fixtures_away_att, fixtures_away_def, fixtures_away_gk]:
        df.columns = new_cols

    fixtures_att = pd.concat([fixtures_home_att, fixtures_away_att], ignore_index=True)
    fixtures_def = pd.concat([fixtures_home_def, fixtures_away_def], ignore_index=True)
    fixtures_gk = pd.concat([fixtures_home_gk, fixtures_away_gk], ignore_index=True)

    fixtures_att1 = fixtures_att.groupby("team", as_index=False).sum()
    fixtures_def1 = fixtures_def.groupby("team", as_index=False).sum()
    fixtures_gk1 = fixtures_gk.groupby("team", as_index=False).sum()

    fixtures_att1["fdr"] = fixtures_att1.iloc[:, 1:].sum(axis=1)
    fixtures_def1["fdr"] = fixtures_def1.iloc[:, 1:].sum(axis=1)
    fixtures_gk1["fdr"] = fixtures_gk1.iloc[:, 1:].sum(axis=1)

    gkp_df = players5[players5["pos"] == "GKP"].merge(fixtures_gk1, on="team", how="left")
    def_df = players5[players5["pos"] == "DEF"].merge(fixtures_def1, on="team", how="left")
    att_df = players5[~players5["pos"].isin(["GKP", "DEF"])].merge(fixtures_att1, on="team", how="left")
    players6 = pd.concat([gkp_df, def_df, att_df], ignore_index=True).sort_values(by="cost", ascending=False).reset_index(drop=True)

    # ---- Add extra player data
    player_data = players[["first_name", "second_name", "ep_next", "chance_of_playing_next_round"]].copy()
    player_data["name"] = player_data["first_name"] + " " + player_data["second_name"]
    player_data = player_data.drop(columns=["first_name", "second_name"])
    player_data = player_data[["name", "ep_next", "chance_of_playing_next_round"]]
    player_data.columns = ["name_fpl", "ep_fpl", "flag_fpl"]
    players8 = players6.merge(player_data, left_on="name", right_on="name_fpl", how="left")

    # xmins
    players8 = players8.merge(xm_manual, left_on="name", right_on="xm_name", how="left")
    players8["xm_ty"] = players8["mins"] / max(1, VAR_GW0)
    players8["xm_ly"] = (players8["mins_ly"] / 38).clip(lower=40).fillna(0)
    players8["xm_max"] = np.where(players8["flag_fpl"].isna(), players8["xm_form"], players8["xm_form"] * (players8["flag_fpl"] / 100))
    players8["xm"] = round((players8["xm_max"] + players8["xm_ty"]) / 2, 2)
    players8["xm"] = np.where(players8["xm_manual"].isna(), players8["xm"], players8["xm_manual"])

    # predicted points
    players9 = players8.fillna(0).copy()
    players9["ep_fpl"] = pd.to_numeric(players9["ep_fpl"], errors="coerce")
    players9["mean_value"] = round(players9[["pred_pp90_form", "pp90_ly", "ep_fpl"]].mean(axis=1), 2)
    players9["mean_value"] = np.where(players9["pp90_ly"] == 0, players9[["pred_pp90_form", "ep_fpl"]].mean(axis=1), players9["mean_value"])
    players9["base_points"] = round((players9["mean_value"] / 90) * players9["xm"], 2)
    players9["bp_copy"] = players9["base_points"]

    players9["gw1"] = round(players9[["op1", "base_points", "bp_copy"]].mean(axis=1), 2)
    players9["gw2"] = round(players9[["op2", "base_points", "bp_copy"]].mean(axis=1), 2)
    players9["gw3"] = round(players9[["op3", "base_points", "bp_copy"]].mean(axis=1), 2)
    players9["gw4"] = round(players9[["op4", "base_points", "bp_copy"]].mean(axis=1), 2)
    players9["gw5"] = round(players9[["op5", "base_points", "bp_copy"]].mean(axis=1), 2)
    players9["gw6"] = round(players9[["op6", "base_points", "bp_copy"]].mean(axis=1), 2)

    players9["predicted_points"] = players9[["gw1", "gw2", "gw3", "gw4", "gw5", "gw6"]].sum(axis=1)
    players9[["op1", "op2", "op3", "op4", "op5", "op6", "fdr"]] = players9[["op1", "op2", "op3", "op4", "op5", "op6", "fdr"]].round(2)

    players10 = players9.sort_values(by="points", ascending=False)
    players10 = players10[np.isfinite(players10["predicted_points"])]

    final_pos = positions[["pos", "id"]].copy()
    final_pos.columns = ["pos_code", "pos_id"]
    players10 = players10.merge(final_pos, left_on="pos", right_on="pos_code", how="left")

    # research output
    player_output = players10[
        ["name", "team", "pos", "cost", "ownership", "points", "mins", "xm", "points_ly", "xg", "xa", "cs", "dc", "predicted_points", "base_points", "mean_value", "xopp90_form", "pred_pp90_form", "pp90_ly", "ep_fpl"]
    ].copy()

    player_output["xg"] = pd.to_numeric(player_output["xg"], errors="coerce")
    player_output["xa"] = pd.to_numeric(player_output["xa"], errors="coerce")

    player_output["xg_p90"] = (player_output["xg"] / (player_output["mins"] / 90)).round(2)
    player_output["xa_p90"] = (player_output["xa"] / (player_output["mins"] / 90)).round(2)
    player_output["cs_p90"] = (player_output["cs"] / (player_output["mins"] / 90)).round(2)
    player_output["dc_p90"] = (player_output["dc"] / (player_output["mins"] / 90)).round(2)

    player_output = player_output[
        ["name", "team", "pos", "cost", "ownership", "points", "mins", "xg_p90", "xa_p90", "cs", "dc", "dc_p90", "xopp90_form", "pred_pp90_form", "base_points", "predicted_points"]
    ].fillna(0)
    player_output = player_output.sort_values(by="predicted_points", ascending=False)

    # pool output (rename gw1..6 to actual gw names)
    output = players10[["id", "name", "team", "pos", "pos_id", "cost", "ownership", "predicted_points", "xm", "fdr", "gw1", "gw2", "gw3", "gw4", "gw5", "gw6"]].copy()
    output = output.rename(
        columns={
            "id": "element",
            "gw1": ctx["VGW_NAME_1"],
            "gw2": ctx["VGW_NAME_2"],
            "gw3": ctx["VGW_NAME_3"],
            "gw4": ctx["VGW_NAME_4"],
            "gw5": ctx["VGW_NAME_5"],
            "gw6": ctx["VGW_NAME_6"],
        }
    )
    output = output.sort_values(by="predicted_points", ascending=False)

    return {
        "ctx": ctx,
        "output": output,
        "player_output": player_output,
        "fdr_att": fixtures_att1,
        "fdr_def": fixtures_def1,
    }


# -----------------------------
# Optimiser layer
# -----------------------------
def _pick_starting_xi_for_week(team_df: pd.DataFrame, week_col: str) -> List[int]:
    """
    Heuristic: pick best XI by points for that week subject to legal formation.
    Returns list of row indices for starters (within team_df).
    """
    df = team_df.copy()
    df[week_col] = pd.to_numeric(df[week_col], errors="coerce").fillna(0)

    # must include 1 GKP
    starters = []
    gk = df[df["pos"] == "GKP"].sort_values(week_col, ascending=False).head(1)
    starters += gk.index.tolist()

    remaining = df.drop(index=starters)

    # choose outfield 10 with formation constraints:
    # DEF 3-5, MID 2-5, FWD 1-3
    # greedy: try all feasible splits, pick best total
    best = None
    out = remaining.copy()

    def top_n(pos: str, n: int) -> pd.DataFrame:
        return out[out["pos"] == pos].sort_values(week_col, ascending=False).head(n)

    for n_def in range(3, 6):
        for n_mid in range(2, 6):
            for n_fwd in range(1, 4):
                if n_def + n_mid + n_fwd != 10:
                    continue
                sel = pd.concat([top_n("DEF", n_def), top_n("MID", n_mid), top_n("FWD", n_fwd)])
                if len(sel) != 10:
                    continue
                total = sel[week_col].sum() + df.loc[starters, week_col].sum()
                if best is None or total > best[0]:
                    best = (total, starters + sel.index.tolist())

    if best is None:
        # fallback: just top 10 outfielders
        sel = out.sort_values(week_col, ascending=False).head(10)
        return starters + sel.index.tolist()

    return best[1]


def optimise_squad(
    pool: pd.DataFrame,
    budget: int = 1000,
    transfers: int = 0,
    current_ids: Optional[List[int]] = None,
    exclude_names: Optional[List[str]] = None,
    exclude_teams: Optional[List[str]] = None,
    include_names: Optional[List[str]] = None,
    optimisation_mode: str = "next_6_gw",
    ctx: Optional[Dict[str, Any]] = None,
) -> Tuple[pd.DataFrame, List[str], List[int]]:
    """
    Returns: final_team_df, current_names, current_ids
    """
    ctx = ctx or get_gw_context()
    df = pool.copy()

    exclude_names = [x.strip() for x in (exclude_names or []) if x and str(x).strip()]
    exclude_teams = [x.strip() for x in (exclude_teams or []) if x and str(x).strip()]
    include_names = [x.strip() for x in (include_names or []) if x and str(x).strip()]

    # apply excludes
    if exclude_names:
        df = df[~df["name"].isin(exclude_names)]
    if exclude_teams:
        df = df[~df["team"].isin(exclude_teams)]

    # objective points column
    if optimisation_mode == "gw1_only":
        obj_col = ctx["VGW_NAME_1"]
        df[obj_col] = pd.to_numeric(df[obj_col], errors="coerce").fillna(0)
        df["obj_points"] = df[obj_col]
    else:
        df["obj_points"] = pd.to_numeric(df["predicted_points"], errors="coerce").fillna(0)

    # current squad markers
    current_ids = current_ids or []
    current_id_set = set(current_ids)
    df["is_current"] = df["element"].isin(current_id_set).astype(int)

    # LP
    prob = pulp.LpProblem("FPL_Squad", pulp.LpMaximize)
    x = {int(r.element): pulp.LpVariable(f"x_{int(r.element)}", 0, 1, cat="Binary") for r in df.itertuples(index=False)}

    # maximise objective
    prob += pulp.lpSum([x[int(r.element)] * float(r.obj_points) for r in df.itertuples(index=False)])

    # squad size
    prob += pulp.lpSum([x[e] for e in x]) == 15

    # budget
    prob += pulp.lpSum([x[int(r.element)] * float(r.cost) for r in df.itertuples(index=False)]) <= float(budget)

    # position counts
    def _count_pos(pos: str) -> pulp.LpAffineExpression:
        return pulp.lpSum([x[int(r.element)] for r in df.itertuples(index=False) if r.pos == pos])

    prob += _count_pos("GKP") == 2
    prob += _count_pos("DEF") == 5
    prob += _count_pos("MID") == 5
    prob += _count_pos("FWD") == 3

    # max 3 per team
    for team in df["team"].unique():
        prob += pulp.lpSum([x[int(r.element)] for r in df.itertuples(index=False) if r.team == team]) <= 3

    # must-includes (by name)
    if include_names:
        name_to_element = df.groupby("name")["element"].apply(list).to_dict()
        for nm in include_names:
            els = name_to_element.get(nm)
            if els:
                prob += pulp.lpSum([x[int(e)] for e in els]) >= 1

    # transfers constraint (simple “keep at least 15 - transfers”)
    if current_ids and transfers is not None and transfers >= 0:
        keep_min = max(0, 15 - int(transfers))
        prob += pulp.lpSum([x[int(r.element)] for r in df.itertuples(index=False) if int(r.element) in current_id_set]) >= keep_min

    # solve
    prob.solve(pulp.PULP_CBC_CMD(msg=False))
    if pulp.LpStatus[prob.status] != "Optimal":
        raise ValueError(f"Optimiser failed: {pulp.LpStatus[prob.status]}")

    chosen = [e for e, var in x.items() if var.value() == 1]
    team_df = df[df["element"].isin(chosen)].copy()

    # attach starting weeks
    week_cols = [ctx["VGW_NAME_1"], ctx["VGW_NAME_2"], ctx["VGW_NAME_3"], ctx["VGW_NAME_4"], ctx["VGW_NAME_5"], ctx["VGW_NAME_6"]]
    existing_week_cols = [c for c in week_cols if c in team_df.columns]

    starters_map = {i: [] for i in team_df.index}
    for w in existing_week_cols:
        starter_idx = _pick_starting_xi_for_week(team_df, w)
        for idx in starter_idx:
            starters_map[idx].append(w)

    team_df["starting_weeks"] = [" ,".join(starters_map[i]).replace(" ,", ",") for i in team_df.index]

    # display ordering
    pos_order = {"GKP": 0, "DEF": 1, "MID": 2, "FWD": 3}
    team_df["pos_sort"] = team_df["pos"].map(pos_order).fillna(99).astype(int)
    team_df = team_df.sort_values(["pos_sort", "obj_points"], ascending=[True, False]).drop(columns=["pos_sort"])

    current_names = sorted(df[df["element"].isin(current_id_set)]["name"].unique().tolist()) if current_ids else []
    return team_df.reset_index(drop=True), current_names, current_ids


# -----------------------------
# Public API (what your app calls)
# -----------------------------
def run_model(
    fpl_id=None,  # unused here (you fetch picks in app)
    transfers=0,
    exclude_names=None,
    exclude_teams=None,
    include_names=None,
    budget=1000,
    picks_data=None,
    transfers_data=None,  # unused in simplified budget logic (kept for signature stability)
    optimisation_mode="next_6_gw",
):
    base = build_base_player_pool()
    ctx = base["ctx"]
    output = base["output"]
    player_output = base["player_output"]
    fdr_att = base["fdr_att"]
    fdr_def = base["fdr_def"]

    current_ids = [p["element"] for p in (picks_data or [])] if picks_data else []

    final_team, current_names, current_ids = optimise_squad(
        pool=output,
        budget=budget,
        transfers=transfers or 0,
        current_ids=current_ids,
        exclude_names=exclude_names,
        exclude_teams=exclude_teams,
        include_names=include_names,
        optimisation_mode=optimisation_mode,
        ctx=ctx,
    )

    # Return tuple shape your app expects
    return (
        final_team,
        output,
        player_output,
        fdr_att,
        fdr_def,
        current_names,
        current_ids,
    )