# -*- coding: utf-8 -*-
"""fpl_app_wip3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12BEgqKMYUbpJuGsuAstEHrTaraxYuzuO
"""

import streamlit as st
import pandas as pd
import numpy as np
import requests

from fpl_model import (
    run_model,
    VAR_GW,
    VAR_GW0,
    VGW_NAME_1,
    VGW_NAME_2,
    VGW_NAME_3,
    VGW_NAME_4,
    VGW_NAME_5,
    VGW_NAME_6,
)

# ================== PAGE CONFIG ==================
st.set_page_config(
    page_title=f"FPL Optimiser – GW{VAR_GW}",
    page_icon="⚽",
    layout="wide",
)

st.title(f"⚽ FPL Squad Optimiser – Gameweek {VAR_GW}")

st.markdown(
    """
This tool builds an optimal FPL squad based on your constraints and our modelled projections.

- **Normal mode**: maximise total points over the next 6 GWs
- **Free Hit mode**: maximise points in this GW only
"""
)

# ================== INPUT FORM ==================
def get_inputs():
    col1, col2, col3 = st.columns(3)

    with col1:
        fpl_id = st.text_input(
            "FPL ID (optional – used to fetch your current team)",
            value="",
            placeholder="e.g. 1234567",
        )
        transfers = st.number_input(
            "Available transfers (for normal mode)",
            min_value=0,
            max_value=15,
            value=1,
            step=1,
        )

    with col2:
        exclude_names = st.text_area(
            "Exclude players (comma separated names)",
            help="Players you do NOT want in the optimised squad.",
        ).split(",")

        include_names = st.text_area(
            "Must-include players (comma separated names)",
            help="Players that MUST be in the optimised squad.",
        ).split(",")

    with col3:
        exclude_teams = st.text_area(
            "Exclude teams (comma separated short names, e.g. LIV, MCI)",
            help="Teams you want to completely avoid.",
        ).split(",")

        budget = st.number_input(
            "Budget (in tenths, e.g. 1000 = £100.0m)",
            min_value=950,
            max_value=1500,
            value=1000,
            step=1,
        )

    st.markdown("---")

    # ===== Optimisation target =====
    opt_label = st.radio(
        "Optimise for:",
        [
            "Next 6 GWs (total points)",
            "This GW only (Free Hit)",
        ],
        index=0,
        help=(
            "Choose whether the optimiser should maximise total points over "
            "the next 6 gameweeks, or just this gameweek (Free Hit style)."
        ),
        horizontal=True,
    )

    if "Free Hit" in opt_label:
        optimisation_mode = "gw1_only"   # optimise only VGW_NAME_1
    else:
        optimisation_mode = "next_6_gw"  # optimise VGW_NAME_1–VGW_NAME_6

    return (
        fpl_id.strip(),
        transfers,
        [n.strip() for n in exclude_names if n.strip()],
        [t.strip() for t in exclude_teams if t.strip()],
        [n.strip() for n in include_names if n.strip()],
        budget,
        optimisation_mode,
    )


# ================== INPUT PARAMETERS ==================
with st.expander("⚙️ Input Parameters", expanded=True):
    (
        fpl_id_input,
        transfers_input,
        exclude_names_input,
        exclude_teams_input,
        include_names_input,
        budget_input,
        optimisation_mode_input,
    ) = get_inputs()

# ===== Fetch picks ONCE and cache them =====
if "picks_data" not in st.session_state:
    st.session_state.picks_data = []

if fpl_id_input:
    try:
        # Use last completed GW (VAR_GW0) to fetch current squad
        picks_url = (
            f"https://fantasy.premierleague.com/api/entry/"
            f"{fpl_id_input}/event/{VAR_GW0}/picks/"
        )
        resp = requests.get(picks_url, timeout=10)
        if resp.status_code == 200:
            data = resp.json()
            st.session_state.picks_data = data.get("picks", [])
        else:
            st.warning(
                f"Could not fetch picks for FPL ID {fpl_id_input} "
                f"(status {resp.status_code}). Optimiser will ignore current team."
            )
            st.session_state.picks_data = []
    except Exception as e:
        st.warning(
            f"Error fetching picks for FPL ID {fpl_id_input}: {e}. "
            "Optimiser will ignore current team."
        )
        st.session_state.picks_data = []
else:
    st.session_state.picks_data = []

# ===== SESSION STATE SETUP =====
for k, v in {
    "final_team": None,
    "raw_output": None,
    "player_output": None,
    "fdr_att": None,
    "fdr_def": None,
    "current_names": [],
}.items():
    if k not in st.session_state:
        st.session_state[k] = v

# ================== RUN BUTTON ==================
if st.button("🚀 Run Model"):
    with st.spinner("Running optimisation..."):
        try:
            (
                final_team,
                output,
                player_output,
                fdr_att,
                fdr_def,
                current_names,
            ) = run_model(
                fpl_id=fpl_id_input if fpl_id_input else None,
                transfers=transfers_input or 0,
                exclude_names=exclude_names_input,
                exclude_teams=exclude_teams_input,
                include_names=include_names_input,
                budget=budget_input,
                picks_data=st.session_state.picks_data,
                optimisation_mode=optimisation_mode_input,
            )

            st.session_state.final_team = final_team
            st.session_state.raw_output = output
            st.session_state.player_output = player_output
            st.session_state.fdr_att = fdr_att
            st.session_state.fdr_def = fdr_def
            st.session_state.current_names = current_names

        except Exception as e:
            st.error(f"Something went wrong while running the model: {e}")

# ======= Helper renderers for tabs 3–5 (always available) =======

def render_research_tab(tab):
    from fpl_model import run_model  # ensure available inside function if not imported globally

    with tab:
        st.subheader("🔬 Research Players Yourself")
        st.markdown("Filter by position to find the key insights")
        st.markdown("See the glossary tab to understand what each metric means...")

        # 🔁 PRE-LOAD BASE MODEL IF NEEDED
        if st.session_state.player_output is None:
            with st.spinner("Building base player model (one-off)..."):
                try:
                    # Neutral / global run:
                    # - No FPL ID
                    # - No transfer limit constraint
                    # - No include/exclude filters
                    # - Standard budget just to satisfy the optimiser
                    (
                        _base_final_team,
                        _base_output,
                        base_player_output,
                        base_fdr_att,
                        base_fdr_def,
                        _base_current_names,
                    ) = run_model(
                        fpl_id=None,
                        transfers=0,
                        exclude_names=[],
                        exclude_teams=[],
                        include_names=[],
                        budget=1000,          # neutral budget
                        picks_data=[],
                        optimisation_mode="next_6_gw",
                    )

                    st.session_state.player_output = base_player_output
                    # Also pre-populate FDR so the Fixture Difficulty tab works too
                    if st.session_state.fdr_att is None:
                        st.session_state.fdr_att = base_fdr_att
                    if st.session_state.fdr_def is None:
                        st.session_state.fdr_def = base_fdr_def

                except Exception as e:
                    st.error(f"Could not pre-load research data: {e}")
                    return

        # If still no data, bail gracefully
        if st.session_state.player_output is None:
            st.info("No player data available yet.")
            return

        research = st.session_state.player_output.sort_values(
            by="predicted_points", ascending=False
        )

        positions = research["pos"].unique().tolist()
        pos_filter = st.multiselect(
            "Filter by position", options=positions, default=positions
        )
        filtered_df = research[research["pos"].isin(pos_filter)].reset_index(drop=True)

        numeric_cols_raw = filtered_df.select_dtypes(include=[np.number]).columns
        styled_raw = (
            filtered_df.style
            .background_gradient(subset=numeric_cols_raw, cmap="RdYlGn")
            .format(precision=2)
        )
        st.dataframe(styled_raw, use_container_width=True, height=800)



def render_fdr_tab(tab):
    with tab:
        st.subheader("⚔️ Fixture Difficulty Rating")

        if st.session_state.fdr_att is None or st.session_state.fdr_def is None:
            st.info("Run the model to populate Fixture Difficulty.")
            return

        st.markdown("### 🔴 Attackers")
        st.markdown(
            "This shows you the average points per **Attacker** for opponents over the next 6 games."
        )

        fdr_att1 = st.session_state.fdr_att.sort_values(by="fdr", ascending=False)
        fdr_att1 = fdr_att1.reset_index(drop=True)

        numeric_cols_att = fdr_att1.select_dtypes(include=[np.number]).columns
        styled_att = (
            fdr_att1.style
            .background_gradient(subset=numeric_cols_att, cmap="Reds")
            .format(precision=2)
        )
        st.dataframe(styled_att, use_container_width=True, height=750)

        st.markdown("---")
        st.markdown("### 🛡️ Defenders")
        st.markdown(
            "This shows you the average points per **Defender** for opponents over the next 6 games."
        )

        fdr_def1 = st.session_state.fdr_def.sort_values(by="fdr", ascending=False)
        fdr_def1 = fdr_def1.reset_index(drop=True)

        numeric_cols_def = fdr_def1.select_dtypes(include=[np.number]).columns
        styled_def = (
            fdr_def1.style
            .background_gradient(subset=numeric_cols_def, cmap="Blues")
            .format(precision=2)
        )
        st.dataframe(styled_def, use_container_width=True, height=750)


def render_glossary_tab(tab):
    with tab:
        st.subheader("📖 Metric Glossary")
        st.markdown("Here’s what each of the key metrics means:")

        glossary = {
            "points": "Total FPL points scored this season (to date).",
            "mins": "Minutes played this season.",
            "points_ly": "Total FPL points last season (LY = last year).",
            "xg": "Expected goals (quality of chances to score).",
            "xg_p90": "Expected goals per 90 minutes.",
            "xa": "Expected assists (quality of chances created).",
            "xa_p90": "Expected assists per 90 minutes.",
            "cs": "Clean sheets (0 goals conceded while on the pitch ≥60’).",
            "dc": "Defensive contributions (clearances + blocks + recoveries + interceptions + tackles).",
            "dc_p90": "Defensive contributions per 90 minutes.",
            "xopp90_form": "Expected Offensive Points Per 90 based on recent form (xG_p90 + xA_p90 converted into FPL points).",
            "pred_pp90_form": "Model’s predicted points per 90 from combined attacking + defensive form.",
            "base_points": "Predicted points adjusted by expected minutes (xMins).",
            "predicted_points": "Predicted points over the next 6 weeks (base points adjusted by fixtures).",
        }

        for metric, desc in glossary.items():
            st.markdown(f"**{metric}** — {desc}")


# ======= Tabs layout =======
# Tabs 3–5 exist always. Tabs 1–2 only after a run.

if st.session_state.final_team is not None and st.session_state.raw_output is not None:

    # ======= Position color map for final squad =======
    def highlight_pos(val):
        color_map = {
            "GKP": "#FFD700",
            "DEF": "#90EE90",
            "MID": "#ADD8E6",
            "FWD": "#FFB6C1",
        }
        return f"background-color: {color_map.get(val, 'white')}"

    tab1, tab2, tab3, tab4, tab5 = st.tabs(
        [
            "🧩 Final Squad",
            "🎯 Captain Ranking",
            "📄 Research Players",
            "📅 Fixture Difficulty",
            "📖 Glossary",
        ]
    )

    # --- Tab 1 — Final Squad ---
    with tab1:
        st.subheader("🧩 Final Squad")

        # Transfer impact vs current team if we have an FPL ID
        current_names = st.session_state.current_names or []
        if current_names:
            st.markdown("### 🔁 Transfer Impact vs Your Current Team")

            current_names_set = set(current_names)
            sel_df = st.session_state.final_team[["name", "team", "pos", "predicted_points"]].copy()
            sel_df["predicted_points"] = pd.to_numeric(
                sel_df["predicted_points"], errors="coerce"
            )

            selected_names = set(sel_df["name"])
            removed_names = sorted(current_names_set - selected_names)
            added_names = sorted(selected_names - current_names_set)

            pool = st.session_state.raw_output.copy()
            if "predicted_points" in pool.columns:
                pool["predicted_points"] = pd.to_numeric(
                    pool["predicted_points"], errors="coerce"
                )

            removed_df = (
                pool.loc[pool["name"].isin(removed_names), ["name", "team", "pos", "predicted_points"]]
                .sort_values("predicted_points", ascending=False)
            )
            added_df = (
                sel_df.loc[sel_df["name"].isin(added_names)]
                .sort_values("predicted_points", ascending=False)
            )

            c1, c2 = st.columns(2)
            with c1:
                st.markdown(f"**Out ({len(removed_df)}):**")
                if removed_df.empty:
                    st.info("No players removed or no current team data.")
                else:
                    st.dataframe(removed_df.round(2), use_container_width=True, height=220)

            with c2:
                st.markdown(f"**In ({len(added_df)}):**")
                if added_df.empty:
                    st.info("No players added.")
                else:
                    st.dataframe(added_df.round(2), use_container_width=True, height=220)

            st.markdown("---")

        # Styled final team table
        st.markdown("### 📋 Optimised 15-man Squad")

        st.session_state.final_team = st.session_state.final_team.reset_index(drop=True)
        numeric_cols1 = st.session_state.final_team.select_dtypes(include=[np.number]).columns
        styled_df = (
            st.session_state.final_team.style
            .applymap(highlight_pos, subset=["pos"])
            .background_gradient(subset=numeric_cols1, cmap="YlGnBu")
            .format(precision=2)
        )
        st.dataframe(styled_df, use_container_width=True, height=600)

        # Download button
        csv = st.session_state.final_team.to_csv(index=False)
        st.download_button(
            "⬇️ Download squad as CSV",
            csv,
            "squad.csv",
            "text/csv",
        )

    # --- Tab 2 — Captain Ranking (Safe vs Punt) ---
    with tab2:
        st.subheader("🎯 Captain Ranking")

        pool = st.session_state.raw_output.copy()

        if VGW_NAME_1 not in pool.columns:
            st.info("GW column not found in output – try re-running the model.")
        else:
            # Ensure numeric types
            pool[VGW_NAME_1] = pd.to_numeric(pool[VGW_NAME_1], errors="coerce")
            if "predicted_points" in pool.columns:
                pool["predicted_points"] = pd.to_numeric(
                    pool["predicted_points"], errors="coerce"
                )
            if "ownership" in pool.columns:
                pool["ownership"] = pd.to_numeric(
                    pool["ownership"], errors="coerce"
                )

            # Basic captain pool
            cols = ["name", "team", "pos", VGW_NAME_1]
            if "predicted_points" in pool.columns:
                cols.append("predicted_points")
            if "ownership" in pool.columns:
                cols.append("ownership")

            cap = pool[cols].copy().dropna(subset=[VGW_NAME_1])

            # Sort anchor: this GW, then total predicted
            sort_cols = [VGW_NAME_1]
            ascending = [False]
            if "predicted_points" in cap.columns:
                sort_cols.append("predicted_points")
                ascending.append(False)

            cap = cap.sort_values(by=sort_cols, ascending=ascending)

            # Rename columns for display
            rename_map = {
                VGW_NAME_1: f"{VGW_NAME_1.upper()} points",
                "predicted_points": "Total points (next 6 GWs)",
                "ownership": "Ownership (%)",
            }
            cap = cap.rename(columns={k: v for k, v in rename_map.items() if k in cap.columns})

            # Thresholds for safe / punt
            st.markdown("Tune the thresholds below to define **safe** vs **punt** captains.")
            c_safe, c_punt = st.columns(2)
            with c_safe:
                safe_min = st.number_input(
                    "Safe pick = ownership ≥",
                    min_value=0.0,
                    max_value=100.0,
                    value=30.0,
                    step=1.0,
                )
            with c_punt:
                punt_max = st.number_input(
                    "Punt pick = ownership ≤",
                    min_value=0.0,
                    max_value=100.0,
                    value=10.0,
                    step=1.0,
                )

            # Split into safe / punt (and ignore rows without ownership)
            if "Ownership (%)" in cap.columns:
                cap_nonnull = cap.dropna(subset=["Ownership (%)"]).copy()
                safe_df = cap_nonnull[cap_nonnull["Ownership (%)"] >= safe_min]
                punt_df = cap_nonnull[cap_nonnull["Ownership (%)"] <= punt_max]
            else:
                st.warning("Ownership data not available – showing a single combined ranking.")
                safe_df = pd.DataFrame()
                punt_df = pd.DataFrame()

            # Combined top ranking (overall)
            st.markdown(
                f"#### 🧮 Overall top captain candidates for **{VGW_NAME_1.upper()}**"
            )
            top_overall = cap.head(20).reset_index(drop=True)
            num_cols_overall = top_overall.select_dtypes(include=[np.number]).columns
            styled_overall = (
                top_overall.style
                .background_gradient(subset=num_cols_overall, cmap="Oranges")
                .format(precision=2)
            )
            st.dataframe(styled_overall, use_container_width=True, height=350)

            st.markdown("---")

            # Safe picks
            st.markdown(
                f"#### 🟢 Safe captains (ownership ≥ {safe_min:.0f}%)"
            )
            if safe_df.empty:
                st.info("No players meet the safe captain threshold with current settings.")
            else:
                safe_top = safe_df.head(15).reset_index(drop=True)
                num_cols_safe = safe_top.select_dtypes(include=[np.number]).columns
                styled_safe = (
                    safe_top.style
                    .background_gradient(subset=num_cols_safe, cmap="Greens")
                    .format(precision=2)
                )
                st.dataframe(styled_safe, use_container_width=True, height=350)

            st.markdown("---")

            # Punt picks
            st.markdown(
                f"#### 🔥 Punt captains (ownership ≤ {punt_max:.0f}%)"
            )
            if punt_df.empty:
                st.info("No players meet the punt captain threshold with current settings.")
            else:
                punt_top = punt_df.head(15).reset_index(drop=True)
                num_cols_punt = punt_top.select_dtypes(include=[np.number]).columns
                styled_punt = (
                    punt_top.style
                    .background_gradient(subset=num_cols_punt, cmap="Reds")
                    .format(precision=2)
                )
                st.dataframe(styled_punt, use_container_width=True, height=350)


    # --- Tab 3–5 always rendered via helpers ---
    render_research_tab(tab3)
    render_fdr_tab(tab4)
    render_glossary_tab(tab5)

else:
    # No final squad yet → show just tabs 3–5
    tab3, tab4, tab5 = st.tabs(
        [
            "📄 Research Players",
            "📅 Fixture Difficulty",
            "📖 Glossary",
        ]
    )
    render_research_tab(tab3)
    render_fdr_tab(tab4)
    render_glossary_tab(tab5)
