# -*- coding: utf-8 -*-
"""Copy of fpl_app_wip1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2LeDxgjW_AxyHzmWo-ncYjQz_AtGc_s
"""

# streamlit_app.py

import streamlit as st
import pandas as pd
import numpy as np
import requests

# Import the model + GW / column names from your separate model file
from fpl_model import (
    run_model,
    VAR_GW,
    VAR_GW0,
    VGW_NAME_1,
    VGW_NAME_2,
    VGW_NAME_3,
    VGW_NAME_4,
    VGW_NAME_5,
    VGW_NAME_6,
)

# ================== PAGE CONFIG ==================
st.set_page_config(
    page_title=f"FPL Optimiser – GW{VAR_GW}",
    page_icon="⚽",
    layout="wide",
)

st.title(f"⚽ FPL Squad Optimiser – Gameweek {VAR_GW}")

st.markdown(
    """
This tool builds an optimal FPL squad based on your constraints and our modelled projections.

- **Normal mode**: maximise total points over the next 6 GWs
- **Free Hit mode**: maximise points in this GW only
"""
)

# ================== INPUT FORM ==================
def get_inputs():
    col1, col2, col3 = st.columns(3)

    with col1:
        fpl_id = st.text_input(
            "FPL ID (optional – used to fetch your current team)",
            value="",
            placeholder="e.g. 1234567",
        )
        transfers = st.number_input(
            "Available transfers (for normal mode)",
            min_value=0,
            max_value=15,
            value=1,
            step=1,
        )

    with col2:
        exclude_names = st.text_area(
            "Exclude players (comma separated names)",
            help="Players you do NOT want in the optimised squad.",
        ).split(",")

        include_names = st.text_area(
            "Must-include players (comma separated names)",
            help="Players that MUST be in the optimised squad.",
        ).split(",")

    with col3:
        exclude_teams = st.text_area(
            "Exclude teams (comma separated short names, e.g. LIV, MCI)",
            help="Teams you want to completely avoid.",
        ).split(",")

        budget = st.number_input(
            "Budget (in tenths, e.g. 1000 = £100.0m)",
            min_value=950,
            max_value=1500,
            value=1000,
            step=1,
        )

    st.markdown("---")

    # ===== Optimisation target =====
    opt_label = st.radio(
        "Optimise for:",
        [
            "Next 6 GWs (total points)",
            "This GW only (Free Hit)",
        ],
        index=0,
        help=(
            "Choose whether the optimiser should maximise total points over "
            "the next 6 gameweeks, or just this gameweek (Free Hit style)."
        ),
        horizontal=True,
    )

    if "Free Hit" in opt_label:
        optimisation_mode = "free_hit"   # optimise only VGW_NAME_1
    else:
        optimisation_mode = "optimise"  # optimise VGW_NAME_1–VGW_NAME_6

    return (
        fpl_id.strip(),
        transfers,
        [n.strip() for n in exclude_names if n.strip()],
        [t.strip() for t in exclude_teams if t.strip()],
        [n.strip() for n in include_names if n.strip()],
        budget,
        optimisation_mode,
    )


# ================== INPUT PARAMETERS ==================
with st.expander("⚙️ Input Parameters", expanded=True):
    (
        fpl_id_input,
        transfers_input,
        exclude_names_input,
        exclude_teams_input,
        include_names_input,
        budget_input,
        optimisation_mode_input,
    ) = get_inputs()

# ===== Fetch picks ONCE and cache them =====
if "picks_data" not in st.session_state:
    st.session_state.picks_data = []

if fpl_id_input:
    try:
        # Use last completed GW (VAR_GW0) to fetch current squad
        picks_url = (
            f"https://fantasy.premierleague.com/api/entry/"
            f"{fpl_id_input}/event/{VAR_GW0}/picks/"
        )
        resp = requests.get(picks_url, timeout=10)
        if resp.status_code == 200:
            data = resp.json()
            st.session_state.picks_data = data.get("picks", [])
        else:
            st.warning(
                f"Could not fetch picks for FPL ID {fpl_id_input} "
                f"(status {resp.status_code}). Optimiser will ignore current team."
            )
            st.session_state.picks_data = []
    except Exception as e:
        st.warning(
            f"Error fetching picks for FPL ID {fpl_id_input}: {e}. "
            "Optimiser will ignore current team."
        )
        st.session_state.picks_data = []
else:
    st.session_state.picks_data = []

# ===== SESSION STATE SETUP =====
for k, v in {
    "final_team": None,
    "raw_output": None,
    "player_output": None,
    "fdr_att": None,
    "fdr_def": None,
    "current_names": [],
}.items():
    if k not in st.session_state:
        st.session_state[k] = v

# ================== RUN BUTTON ==================
if st.button("🚀 Run Model"):
    with st.spinner("Running optimisation..."):
        try:
            (
                final_team,
                output,
                player_output,
                fdr_att,
                fdr_def,
                current_names,
            ) = run_model(
                fpl_id=fpl_id_input if fpl_id_input else None,
                transfers=transfers_input or 0,
                exclude_names=exclude_names_input,
                exclude_teams=exclude_teams_input,
                include_names=include_names_input,
                budget=budget_input,
                picks_data=st.session_state.picks_data,
                optimisation_mode=optimisation_mode_input,  # <<< NEW
            )

            st.session_state.final_team = final_team
            st.session_state.raw_output = output
            st.session_state.player_output = player_output
            st.session_state.fdr_att = fdr_att
            st.session_state.fdr_def = fdr_def
            st.session_state.current_names = current_names

        except Exception as e:
            st.error(f"Something went wrong while running the model: {e}")

# ================== OUTPUT TABS ==================
if st.session_state.final_team is not None:
    st.success("✅ Optimisation complete! See results below.")

    tab1, tab2, tab3, tab4 = st.tabs(
        ["🧩 Final Squad", "📊 All Players", "📈 FDR – Attack", "🛡️ FDR – Defence"]
    )

    # -------- TAB 1: Final Squad --------
    with tab1:
        team_df = st.session_state.final_team.copy()

        # Basic summary
        total_cost = team_df["cost"].sum() / 10.0
        if optimisation_mode_input == "free_hit":
            total_points = team_df[VGW_NAME_1].sum()
            opt_desc = f"Maximising points in **{VGW_NAME_1.upper()}** only."
        else:
            # Sum across all GW columns in the optimised window
            gw_cols = [VGW_NAME_1, VGW_NAME_2, VGW_NAME_3, VGW_NAME_4, VGW_NAME_5, VGW_NAME_6]
            gw_cols = [c for c in gw_cols if c in team_df.columns]
            total_points = team_df[gw_cols].sum().sum()
            opt_desc = "Maximising **total points over the next 6 gameweeks**."

        c1, c2, c3 = st.columns(3)
        c1.metric("Total cost (£m)", f"{total_cost:.1f}")
        c2.metric("Projected points", f"{total_points:.1f}")
        c3.write(opt_desc)

        st.markdown("### 🧩 Selected Squad")
        st.dataframe(
            team_df.reset_index(drop=True),
            use_container_width=True,
        )

    # --- Tab 2 — Summary
    with tab2:
        st.metric("💰 Total Cost", f"{st.session_state.final_team['cost'].sum():.2f}")
        st.metric("📈 Total Points", f"{st.session_state.final_team['predicted_points'].sum():.2f}")
        st.markdown("---")

        ft = st.session_state.final_team.copy()

        # ===== Captain Ranking (Top 3 by gw) =====
        st.subheader("🧢 Captain Ranking (Next GW)")
        if VGW_NAME_1 in ft.columns and "name" in ft.columns:
            top3 = ft.dropna(subset=[VGW_NAME_1]).nlargest(3, VGW_NAME_1)
            top3 = top3[["name","team","pos",VGW_NAME_1,"predicted_points"]]
            top3[VGW_NAME_1] = top3[VGW_NAME_1].round(2)
            top3["predicted_points"] = top3["predicted_points"].round(2)
            top3.columns= ["name","team","pos","Points prediction upcoming week","Points prediction next 6 weeks"]
            top3 = top3.reset_index(drop=True)

            numeric_cols_t3 = top3.select_dtypes(include=[np.number]).columns
            styled_t3 = top3.style.background_gradient(subset=numeric_cols_t3, cmap="Purples").format(precision=2)
            st.table(styled_t3)
        else:
            st.info("GW data not available in current output.")

        st.markdown("---")

        # ===== Underperformers (Bottom 5 by predicted_points) =====
        st.subheader("⬇️ Who is getting the chop soon? - Lowest predicted points over next 6 weeks")
        if "predicted_points" in ft.columns and "name" in ft.columns:
            bottom5 = ft.dropna(subset=["predicted_points"]).nsmallest(5, "predicted_points")
            bottom5 = bottom5[["name","team","pos",VGW_NAME_1,"predicted_points"]]
            bottom5[VGW_NAME_1] = bottom5[VGW_NAME_1].round(2)
            bottom5["predicted_points"] = bottom5["predicted_points"].round(2)
            bottom5.columns= ["name","team","pos","Points prediction upcoming week","Points prediction next 6 weeks"]
            bottom5 = bottom5.reset_index(drop=True)

            numeric_cols_b5 = bottom5.select_dtypes(include=[np.number]).columns
            styled_b5 = bottom5.style.background_gradient(subset=numeric_cols_b5, cmap="Oranges").format(precision=2)
            st.table(styled_b5)
        else:
            st.info("Predicted points not available in current output.")


    # --- Tab 3 — Raw Output with Position Filter ---
    with tab3:
        st.subheader("🔬 Research Players Yourself")
        st.markdown("Filter by position to find the key insights")
        st.markdown("See the glossary tab to understand what each metrics means...")

        research = st.session_state.player_output.sort_values(by="predicted_points", ascending=False)

        positions = research['pos'].unique().tolist()
        pos_filter = st.multiselect("Filter by position", options=positions, default=positions)
        filtered_df = research[research['pos'].isin(pos_filter)]
        filtered_df = filtered_df.reset_index(drop=True)

        numeric_cols_raw = filtered_df.select_dtypes(include=[np.number]).columns
        styled_raw = filtered_df.style.hide(axis="index").background_gradient(subset=numeric_cols_raw, cmap="RdYlGn").format(precision=2)
        st.dataframe(styled_raw, use_container_width=True, height=1000)

    # --- Tab 4 — Fixture Difficulty ---
    with tab4:
        st.subheader("⚔️ Fixture Difficulty Rating")

        st.markdown("### 🔴 Attackers")
        st.markdown("This shows you the average points per Attacker for opponents over the next 6 games.")
        fdr_att1 = st.session_state.fdr_att.sort_values(by="fdr", ascending=False)
        fdr_att1 = fdr_att1.reset_index(drop=True)

        numeric_cols_att = fdr_att1.select_dtypes(include=[np.number]).columns
        styled_att = fdr_att1.style.hide(axis="index").background_gradient(subset=numeric_cols_att, cmap="Reds").format(precision=2)
        st.dataframe(styled_att, use_container_width=True, height=750)

        st.markdown("---")

        st.markdown("### 🛡️ Defenders")
        st.markdown("This shows you the average points per Defender for opponents over the next 6 games.")
        fdr_def1 = st.session_state.fdr_def.sort_values(by="fdr", ascending=False)
        fdr_def1 = fdr_def1.reset_index(drop=True)

        numeric_cols_def = fdr_def1.select_dtypes(include=[np.number]).columns
        styled_def = fdr_def1.style.hide(axis="index").background_gradient(subset=numeric_cols_def, cmap="Blues").format(precision=2)
        st.dataframe(styled_def, use_container_width=True, height=750)

    # --- Tab 5 — Glossary ---
    with tab5:
        st.subheader("📖 Metric Glossary")
        st.markdown("Here’s what each of the key metrics means:")

        glossary = {
            "points": "Total FPL points scored this season (to date).",
            "mins": "Minutes played this season.",
            "points_ly": "Total FPL points last season (LY = last year).",
            "xg": "Expected goals (quality of chances taken).",
            "xg_p90": "Expected goals per 90 minutes.",
            "xa": "Expected assists (quality of chances created).",
            "xa_p90": "Expected assists per 90 minutes.",
            "cs": "Clean sheets (team conceded 0 goals while player was on the pitch for ≥60’).",
            "dc": "Defensive contributions (Clearances + Blocks + Recoveries + Interceptions + Tackles).",
            "dcp90": "Defensive contributions per 90 minutes.",
            "xopp90_form": "Expected Offensive Points Per 90 based on form (xg_p90 + xa_p90 multiplied by points they get for each action).",
            "pred_pp90": "Our predicted number of points for the player.",
            "base_points": "Predicted points adjusted by expected minutes.",
            "predicted_points": "Predicted points over 6 weeks (base points adjusted by opponents form.)"
        }

        # Display nicely
        for metric, desc in glossary.items():
            st.markdown(f"**{metric}** — {desc}")

else:
    st.info("Set your parameters and click **🚀 Run Model** to see results.")