# -*- coding: utf-8 -*-
"""fpl_app_wip1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HiMQFgISaXJNp6-xwKvVMRVR7_BQKnn
"""

# streamlit_app.py

import streamlit as st
import pandas as pd
import numpy as np
import requests

# Import the model + GW / column names from your separate model file
from fpl_model import (
    run_model,
    VAR_GW,
    VAR_GW0,
    VGW_NAME_1,
    VGW_NAME_2,
    VGW_NAME_3,
    VGW_NAME_4,
    VGW_NAME_5,
    VGW_NAME_6,
)

# ================== PAGE CONFIG ==================
st.set_page_config(
    page_title=f"FPL Optimiser – GW{VAR_GW}",
    page_icon="⚽",
    layout="wide",
)

st.title(f"⚽ FPL Squad Optimiser – Gameweek {VAR_GW}")

st.markdown(
    """
This tool builds an optimal FPL squad based on your constraints and our modelled projections.

- **Normal mode**: maximise total points over the next 6 GWs
- **Free Hit mode**: maximise points in this GW only
"""
)

# ================== INPUT FORM ==================
def get_inputs():
    col1, col2, col3 = st.columns(3)

    with col1:
        fpl_id = st.text_input(
            "FPL ID (optional – used to fetch your current team)",
            value="",
            placeholder="e.g. 1234567",
        )
        transfers = st.number_input(
            "Available transfers (for normal mode)",
            min_value=0,
            max_value=15,
            value=1,
            step=1,
        )

    with col2:
        exclude_names = st.text_area(
            "Exclude players (comma separated names)",
            help="Players you do NOT want in the optimised squad.",
        ).split(",")

        include_names = st.text_area(
            "Must-include players (comma separated names)",
            help="Players that MUST be in the optimised squad.",
        ).split(",")

    with col3:
        exclude_teams = st.text_area(
            "Exclude teams (comma separated short names, e.g. LIV, MCI)",
            help="Teams you want to completely avoid.",
        ).split(",")

        budget = st.number_input(
            "Budget (in tenths, e.g. 1000 = £100.0m)",
            min_value=950,
            max_value=1500,
            value=1000,
            step=1,
        )

    st.markdown("---")

    # ===== Optimisation target =====
    opt_label = st.radio(
        "Optimise for:",
        [
            "Next 6 GWs (total points)",
            "This GW only (Free Hit)",
        ],
        index=0,
        help=(
            "Choose whether the optimiser should maximise total points over "
            "the next 6 gameweeks, or just this gameweek (Free Hit style)."
        ),
        horizontal=True,
    )

    if "Free Hit" in opt_label:
        optimisation_mode = "free_hit"   # optimise only VGW_NAME_1
    else:
        optimisation_mode = "optimise"  # optimise VGW_NAME_1–VGW_NAME_6

    return (
        fpl_id.strip(),
        transfers,
        [n.strip() for n in exclude_names if n.strip()],
        [t.strip() for t in exclude_teams if t.strip()],
        [n.strip() for n in include_names if n.strip()],
        budget,
        optimisation_mode,
    )


# ================== INPUT PARAMETERS ==================
with st.expander("⚙️ Input Parameters", expanded=True):
    (
        fpl_id_input,
        transfers_input,
        exclude_names_input,
        exclude_teams_input,
        include_names_input,
        budget_input,
        optimisation_mode_input,
    ) = get_inputs()

# ===== Fetch picks ONCE and cache them =====
if "picks_data" not in st.session_state:
    st.session_state.picks_data = []

if fpl_id_input:
    try:
        # Use last completed GW (VAR_GW0) to fetch current squad
        picks_url = (
            f"https://fantasy.premierleague.com/api/entry/"
            f"{fpl_id_input}/event/{VAR_GW0}/picks/"
        )
        resp = requests.get(picks_url, timeout=10)
        if resp.status_code == 200:
            data = resp.json()
            st.session_state.picks_data = data.get("picks", [])
        else:
            st.warning(
                f"Could not fetch picks for FPL ID {fpl_id_input} "
                f"(status {resp.status_code}). Optimiser will ignore current team."
            )
            st.session_state.picks_data = []
    except Exception as e:
        st.warning(
            f"Error fetching picks for FPL ID {fpl_id_input}: {e}. "
            "Optimiser will ignore current team."
        )
        st.session_state.picks_data = []
else:
    st.session_state.picks_data = []

# ===== SESSION STATE SETUP =====
for k, v in {
    "final_team": None,
    "raw_output": None,
    "player_output": None,
    "fdr_att": None,
    "fdr_def": None,
    "current_names": [],
}.items():
    if k not in st.session_state:
        st.session_state[k] = v

# ================== RUN BUTTON ==================
if st.button("🚀 Run Model"):
    with st.spinner("Running optimisation..."):
        try:
            (
                final_team,
                output,
                player_output,
                fdr_att,
                fdr_def,
                current_names,
            ) = run_model(
                fpl_id=fpl_id_input if fpl_id_input else None,
                transfers=transfers_input or 0,
                exclude_names=exclude_names_input,
                exclude_teams=exclude_teams_input,
                include_names=include_names_input,
                budget=budget_input,
                picks_data=st.session_state.picks_data,
                optimisation_mode=optimisation_mode_input,  # <<< NEW
            )

            st.session_state.final_team = final_team
            st.session_state.raw_output = output
            st.session_state.player_output = player_output
            st.session_state.fdr_att = fdr_att
            st.session_state.fdr_def = fdr_def
            st.session_state.current_names = current_names

        except Exception as e:
            st.error(f"Something went wrong while running the model: {e}")

# ================== OUTPUT TABS ==================
if st.session_state.final_team is not None:
    st.success("✅ Optimisation complete! See results below.")

    tab1, tab2, tab3, tab4 = st.tabs(
        ["🧩 Final Squad", "📊 All Players", "📈 FDR – Attack", "🛡️ FDR – Defence"]
    )

    # -------- TAB 1: Final Squad --------
    with tab1:
        team_df = st.session_state.final_team.copy()

        # Basic summary
        total_cost = team_df["cost"].sum() / 10.0
        if optimisation_mode_input == "free_hit":
            total_points = team_df[VGW_NAME_1].sum()
            opt_desc = f"Maximising points in **{VGW_NAME_1.upper()}** only."
        else:
            # Sum across all GW columns in the optimised window
            gw_cols = [VGW_NAME_1, VGW_NAME_2, VGW_NAME_3, VGW_NAME_4, VGW_NAME_5, VGW_NAME_6]
            gw_cols = [c for c in gw_cols if c in team_df.columns]
            total_points = team_df[gw_cols].sum().sum()
            opt_desc = "Maximising **total points over the next 6 gameweeks**."

        c1, c2, c3 = st.columns(3)
        c1.metric("Total cost (£m)", f"{total_cost:.1f}")
        c2.metric("Projected points", f"{total_points:.1f}")
        c3.write(opt_desc)

        st.markdown("### 🧩 Selected Squad")
        st.dataframe(
            team_df.reset_index(drop=True),
            use_container_width=True,
        )

    # -------- TAB 2: All Players --------
    with tab2:
        st.markdown("### 📊 Player Model Output")

        po = st.session_state.player_output.copy()
        st.dataframe(
            po.reset_index(drop=True),
            use_container_width=True,
        )

    # -------- TAB 3: FDR – Attack --------
    with tab3:
        st.markdown("### 📈 Fixture Difficulty – Attack")
        fa = st.session_state.fdr_att.copy()
        st.dataframe(
            fa.reset_index(drop=True),
            use_container_width=True,
        )

    # -------- TAB 4: FDR – Defence --------
    with tab4:
        st.markdown("### 🛡️ Fixture Difficulty – Defence")
        fd = st.session_state.fdr_def.copy()
        st.dataframe(
            fd.reset_index(drop=True),
            use_container_width=True,
        )

else:
    st.info("Set your parameters and click **🚀 Run Model** to see results.")